### ISSUE TITLE
Werkzeug 0.11 with Flask 0.10.1 and 'app.debug = True' won't start.

### ISSUE THREAD

**Issue by ollien** [mitsuhiko/werkzeug#798]
I wrote the following test script to demonstrate the issue

```py
import flask

app = flask.Flask(__name__)

@app.route("/")
def helloWorld():
        return "Hello world!"

app.debug = True
app.run()
```

Running it with Flask 0.10.1 and Werkzeug 0.11 raises this error
```
Traceback (most recent call last):
  File "flask-test", line 10, in <module>
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 633, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/debug/__init__.py", line 169, in __init__
    if self.pin is None:
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/debug/__init__.py", line 179, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/debug/__init__.py", line 96, in get_pin_and_cookie_name
    h.update('cookiesalt')
TypeError: Unicode-objects must be encoded before hashing
```

If I downgrade Werkzeug to 0.10.4, it runs without a hitch. However, I can make this run with Werkzeug 0.11 if I remove the `app.debug = True`.

**Comment by ThomasWaldmann** [comment]
Same here.

**Comment by hhamalai** [comment]
This breaks some automated tests which now apparently with this patch require interactive input.

**Comment by kfrendrich** [comment]
+1

**Comment by imbaczek** [comment]
can confirm on python 3.4.1.

**Comment by ResidentMario** [comment]
I asked the same question on StackOverflow: http://stackoverflow.com/questions/33602708/quickstart-flask-application-failing-for-some-reason/33603641#33603641

**Comment by matthewgao** [comment]
+1

**Comment by FalFire** [comment]
+1

**Comment by glothriel** [comment]
+1 Already failed on 2 separate systems - arch/ubuntu 14.04 (packages installed with pip)

**Comment by aminjam** [comment]
+1 We are seeing the same issue as of V0.11

**Comment by davidism** [comment]
OK, everyone has the problem.  There are already three pull requests fixing it.  Saying "+1" isn't going to fix if faster, or make it more obvious that it's a problem.  If you don't have something constructive to say about the issue beyond "+1", refrain from adding noise to everyone's notification box.

**Comment by bufke** [comment]
Affects django too. Python 3.4. Django 1.8.6. [Stacktrace](http://pastebin.com/Jzz7YLAE)

**Comment by qcho** [comment]
pull/801 elegante, works. Lot's of frameworks affected. tutorials not working... I think only putting +1 for a pull request should be enough.

**Comment by Rawks** [comment]
+1, just tested in python 3.5

**Comment by foxlet** [comment]
Failed on OS X 10.10.5 (with Py 3.4.1, Werkzeug 0.11)

**Comment by mitsuhiko** [comment]
This is fixed now in 0.11.1.

**Comment by jscholes** [comment]
I'm still experiencing this issue, even with 0.12-dev straight from GitHub.  I'm on Windows and the traceback references line 169 in werkzeug\debug\__init__.py.

For the moment I'm getting around it by setting WERKZEUG_DEBUG_PIN to "off", but I don't imagine this is a particuilarly good solution, especially not for apps requiring the use of cookies.

**Comment by untitaker** [comment]
@jscholes We recently pushed a release that fixes an almost identical bug. Could you post the full traceback in a new issue? Thanks!
